version: "3.8"
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    networks:
      - sales-network

  product-service:
    build: ./product-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://product-db:3306/product_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - product-db
    networks:
      - sales-network

  product-db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: product_db
    ports:
      - "3307:3306"
    volumes:
      - product-db-data:/var/lib/mysql
    networks:
      - sales-network

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://order-db:3306/order_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - order-db
    networks:
      - sales-network

  order-db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: order_db
    ports:
      - "3308:3306"
    volumes:
      - order-db-data:/var/lib/mysql
    networks:
      - sales-network

  customer-service:
    build: ./customer-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://customer-db:3306/customer_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - customer-db
    networks:
      - sales-network

  customer-db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: customer_db
    ports:
      - "3309:3306"
    volumes:
      - customer-db-data:/var/lib/mysql
    networks:
      - sales-network

  payment-service:
    build: ./payment-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://payment-db:3306/payment_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - payment-db
    networks:
      - sales-network

  payment-db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: payment_db
    ports:
      - "3310:3306"
    volumes:
      - payment-db-data:/var/lib/mysql
    networks:
      - sales-network

  inventory-service:
    build: ./inventory-service
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://inventory-db:3306/inventory_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - inventory-db
    networks:
      - sales-network

  inventory-db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: inventory_db
    ports:
      - "3311:3306"
    volumes:
      - inventory-db-data:/var/lib/mysql
    networks:
      - sales-network

  shipping-service:
    build: ./shipping-service
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://shipping-db:3306/shipping_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - shipping-db
    networks:
      - sales-network

  shipping-db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shipping_db
    ports:
      - "3312:3306"
    volumes:
      - shipping-db-data:/var/lib/mysql
    networks:
      - sales-network

volumes:
  product-db-data:
  order-db-data:
  customer-db-data:
  payment-db-data:
  inventory-db-data:
  shipping-db-data:

networks:
  sales-network:
    driver: bridge
