server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://product-service:8081
          predicates:
            - Path=/api/products/**
        - id: order-service
          uri: http://order-service:8082
          predicates:
            - Path=/api/orders/**
        - id: customer-service
          uri: http://customer-service:8083
          predicates:
            - Path=/api/customers/**
        - id: payment-service
          uri: http://payment-service:8084
          predicates:
            - Path=/api/payments/**
        - id: inventory-service
          uri: http://inventory-service:8085
          predicates:
            - Path=/api/inventory/**
        - id: shipping-service
          uri: http://shipping-service:8086
          predicates:
            - Path=/api/shippings/**