server:
  port: 8086

spring:
  application:
    name: shipping-service
  datasource:
    url: jdbc:mariadb://shipping-db:3306/shipping_db
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

resilience4j:
  circuitbreaker:
    instances:
      shippingService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      shippingService:
        maxAttempts: 3
        waitDuration: 500
  ratelimiter:
    instances:
      shippingService:
        limitForPeriod: 10
        limitRefreshPeriod: 1000
        timeoutDuration: 0
  timelimiter:
    instances:
      shippingService:
        timeoutDuration: 2000