version: "3.8"
services:
  product-service:
    build: .
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://product-db:3306/product_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - product-db
    networks:
      - sales-network

  product-db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: product_db
    ports:
      - "3307:3306"
    volumes:
      - product-db-data:/var/lib/mysql
    networks:
      - sales-network

volumes:
  product-db-data:

networks:
  sales-network:
    driver: bridge
