version: "3.8"
services:
  payment-service:
    build: .
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://payment-db:3306/payment_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - payment-db
    networks:
      - sales-network

  payment-db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: payment_db
    ports:
      - "3310:3306"
    volumes:
      - payment-db-data:/var/lib/mysql
    networks:
      - sales-network

volumes:
  payment-db-data:

networks:
  sales-network:
    driver: bridge
