version: "3.8"
services:
  shipping-service:
    build: .
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://shipping-db:3306/shipping_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - shipping-db
    networks:
      - sales-network

  shipping-db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shipping_db
    ports:
      - "3312:3306"
    volumes:
      - shipping-db-data:/var/lib/mysql
    networks:
      - sales-network

volumes:
  shipping-db-data:

networks:
  sales-network:
    driver: bridge
